root: .
extensions:
    - .js
default-excludes: true
excludes: ['**/core/utils/**']
embed-source: false
variable: __coverage__
compact: true
preserve-comments: false
complete-copy: false
save-baseline: false
baseline-file: ./coverage/coverage-baseline.json
include-all-sources: false
include-pid: false
es-modules: false
# instrumentation:
#     root: src